name: mercadinho
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  auto_size_text: ^3.0.0
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.4.4
  cupertino_icons: ^1.0.6
  dotted_border: ^2.1.0
  firebase_auth: ^5.3.1
  firebase_core: ^3.7.0
  firebase_helpers: ^0.7.0
  firebase_storage: ^12.3.2
  flutter:
    sdk: flutter
  flutter_map: ^7.0.2
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  provider: ^6.1.2
  table_calendar: ^3.1.2
  uuid: ^4.5.1
  video_player: ^2.9.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/ # Diretório para imagens
    - assets/banners/ # Diretório para ícones
    - assets/videos/ # Diretório para vídeos
    - assets/fonts/ # Diretório para fontes personalizadas
